module.exports = {
  testEnvironment: "node",
  setupFilesAfterEnv: ["<rootDir>/tests/setupTests.js"],
  testMatch: ["**/*.test.js"],
  maxWorkers: 1,
  maxConcurrency: 1,
  collectCoverage: true,
  collectCoverageFrom: [
    "**/*.{js,jsx,ts,tsx}",
    "!index.js",
    "!middleware/**",
    // "!routes/**",
    "!prisma/**",
    "!generated/**",
    "!coverage/**",
    "controllers/budgetController.js",
    "controllers/categoryController.js",
    "controllers/goalController.js",
    "controllers/transactionController.js",
    "controllers/userController.js",
  ],
  coverageReporters: ["text", "html"],
  coverageDirectory: "coverage",
};
